/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author alunolages
 */
public class LoginUsuario extends javax.swing.JPanel {
    
    /**
     * Creates new form LoginUsuario
     */
    public LoginUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_LoginUsuario = new javax.swing.JLabel();
        JL_Senha = new javax.swing.JLabel();
        JL_Nome1 = new javax.swing.JLabel();
        CampoDeTexto_Nome1 = new javax.swing.JTextField();
        CampoDeTexto_Senha = new javax.swing.JPasswordField();
        BT_Login = new javax.swing.JButton();
        BT_Cadastrar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JL_LoginUsuario.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        JL_LoginUsuario.setText("Login Usuario");

        JL_Senha.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        JL_Senha.setText("Senha:");

        JL_Nome1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        JL_Nome1.setText("Nome:");

        BT_Login.setBackground(new java.awt.Color(0, 255, 255));
        BT_Login.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BT_Login.setText("Login");
        BT_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_LoginMouseClicked(evt);
            }
        });

        BT_Cadastrar1.setBackground(new java.awt.Color(0, 255, 255));
        BT_Cadastrar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BT_Cadastrar1.setText("Cadastrar");
        BT_Cadastrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_Cadastrar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JL_LoginUsuario)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_Cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_Nome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(CampoDeTexto_Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_Senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoDeTexto_Senha)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_LoginUsuario)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoDeTexto_Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Nome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JL_Senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoDeTexto_Senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_Cadastrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Cadastrar1MouseClicked
        String senha = String.valueOf(CampoDeTexto_Senha.getPassword());
        if(CampoDeTexto_Nome1.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Por favor, digite o nome do usuario!");
        }
        else{
            if(senha.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Por favor, digite a senha!");
            }
            else{
                Main.Main.controller.CadastrarUsuario(CampoDeTexto_Nome1.getText(), senha);
            }
        }
    }//GEN-LAST:event_BT_Cadastrar1MouseClicked

    private void BT_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_LoginMouseClicked
        String senha = String.valueOf(CampoDeTexto_Senha.getPassword());
        boolean verifica = Main.Main.controller.BotaoLogar(CampoDeTexto_Nome1.getText(), senha);
        if(verifica == true){
            Main.Main.controller.MenuEmrpesas(CampoDeTexto_Nome1.getText(), senha);
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuario ou senha inválidas!");
        }
    }//GEN-LAST:event_BT_LoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cadastrar1;
    private javax.swing.JButton BT_Login;
    private javax.swing.JTextField CampoDeTexto_Nome1;
    private javax.swing.JPasswordField CampoDeTexto_Senha;
    private javax.swing.JLabel JL_LoginUsuario;
    private javax.swing.JLabel JL_Nome1;
    private javax.swing.JLabel JL_Senha;
    // End of variables declaration//GEN-END:variables
}
