/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import static Main.Main.controller;
import Model.Conexao;
import Model.Empresa;
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author alunolages
 */
public class MenuEmpresas extends javax.swing.JPanel {

    private ImageIcon ImagemLupa;
    private String imagem = "/Image/Lupa-removebg-preview.png";
    private int Enter = 0;
    private int idUsuario;
    private Conexao conexao = new Conexao();
    
    
    DefaultListModel ModeloLista;
    /**
     * Creates new form LoginUsuario
     */
    public MenuEmpresas() {
        initComponents();
        
        int larguraMaxima = 53; // Largura máxima da JLabel
        int alturaMaxima = 47; // Altura máxima da JLabel

        ImageIcon icon = new ImageIcon(getClass().getResource(this.imagem));
        Image img = icon.getImage();
        
        Image novaImagem = img.getScaledInstance(larguraMaxima, alturaMaxima, Image.SCALE_SMOOTH);

        ImageIcon imagemRedimensionada = new ImageIcon(novaImagem);
        JL_Lupa.setIcon(imagemRedimensionada);
        
        Lista.setVisible(false);
        
        ModeloLista = new DefaultListModel();
        
        Lista.setModel(ModeloLista);
        
        this.conexao = Main.Main.controller.getConexao();
        
        this.idUsuario = Main.Main.controller.getIdUsuario();
        
        //conexao.conecta();;
        
    }
    
    public void ListaDePesquisa() {
        try {
            String pesquisa = CampoDeTexto_Pesquisa.getText().toLowerCase();
            ModeloLista.removeAllElements();
            int v = 0;

            for (Empresa empresa : controller.getEmpresas()) {
                if (empresa.getNome().toLowerCase().startsWith(pesquisa) && v < 4) {
                    ModeloLista.addElement(empresa.getNome());
                    v++;
                }
            }

            Lista.setVisible(v >= 1);

            ResultadoPesquisa();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na pesquisa: " + erro.getMessage());
        }
    }

    public void MostrarPesquisa() {
        int linha = Lista.getSelectedIndex();
        if (linha >= 0) {
            String nome = (String) ModeloLista.getElementAt(linha);
            for (Empresa empresa : controller.getEmpresas()) {
                if (empresa.getNome().equalsIgnoreCase(nome)) {
                    CampoDeTexto_Nome.setText(empresa.getNome());
                    CampoDeTexto_CNPJ.setText(empresa.getCnpj());
                    break;
                }
            }
        }
    }

    public void ResultadoPesquisa() {
        int linha = Lista.getSelectedIndex();
        if (linha >= 0) {
            String nome = (String) ModeloLista.getElementAt(linha);
            for (Empresa empresa : controller.getEmpresas()) {
                if (empresa.getNome().equalsIgnoreCase(nome)) {
                    CampoDeTexto_Nome.setText(empresa.getNome());
                    CampoDeTexto_CNPJ.setText(empresa.getCnpj());
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_MenuEmpresas = new javax.swing.JLabel();
        JL_CNPJ = new javax.swing.JLabel();
        BT_Voltar = new javax.swing.JButton();
        BT_Cadastrar1 = new javax.swing.JButton();
        BT_Entrar1 = new javax.swing.JButton();
        JL_Nome2 = new javax.swing.JLabel();
        CampoDeTexto_Nome = new javax.swing.JTextField();
        CampoDeTexto_CNPJ = new javax.swing.JTextField();
        Painel_Pesquisa = new javax.swing.JPanel();
        JL_Lupa = new javax.swing.JLabel();
        CampoDeTexto_Pesquisa = new javax.swing.JTextField();
        Lista = new javax.swing.JList<>();
        BT_Excluir = new javax.swing.JButton();
        BT_ExcluirUsuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        JL_MenuEmpresas.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        JL_MenuEmpresas.setText("Menu Empresas");

        JL_CNPJ.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        JL_CNPJ.setText("CNPJ:");

        BT_Voltar.setBackground(new java.awt.Color(0, 255, 255));
        BT_Voltar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BT_Voltar.setText("Voltar");
        BT_Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_VoltarMouseClicked(evt);
            }
        });

        BT_Cadastrar1.setBackground(new java.awt.Color(0, 255, 255));
        BT_Cadastrar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BT_Cadastrar1.setText("Cadastrar");
        BT_Cadastrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_Cadastrar1MouseClicked(evt);
            }
        });

        BT_Entrar1.setBackground(new java.awt.Color(0, 255, 255));
        BT_Entrar1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BT_Entrar1.setText("Login");
        BT_Entrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_Entrar1MouseClicked(evt);
            }
        });

        JL_Nome2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        JL_Nome2.setText("Nome:");

        Painel_Pesquisa.setBackground(new java.awt.Color(153, 255, 255));
        Painel_Pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Painel_PesquisaMouseClicked(evt);
            }
        });

        JL_Lupa.setText("jLabel1");

        CampoDeTexto_Pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoDeTexto_PesquisaMouseClicked(evt);
            }
        });
        CampoDeTexto_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDeTexto_PesquisaActionPerformed(evt);
            }
        });
        CampoDeTexto_Pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoDeTexto_PesquisaKeyReleased(evt);
            }
        });

        Lista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Painel_PesquisaLayout = new javax.swing.GroupLayout(Painel_Pesquisa);
        Painel_Pesquisa.setLayout(Painel_PesquisaLayout);
        Painel_PesquisaLayout.setHorizontalGroup(
            Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(JL_Lupa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoDeTexto_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        Painel_PesquisaLayout.setVerticalGroup(
            Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_PesquisaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CampoDeTexto_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JL_Lupa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BT_Excluir.setBackground(new java.awt.Color(0, 255, 255));
        BT_Excluir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BT_Excluir.setText("Excluir");
        BT_Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ExcluirMouseClicked(evt);
            }
        });

        BT_ExcluirUsuario.setBackground(new java.awt.Color(0, 255, 255));
        BT_ExcluirUsuario.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        BT_ExcluirUsuario.setText("Excluir Usuario");
        BT_ExcluirUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ExcluirUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(JL_MenuEmpresas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(JL_CNPJ)
                                .addGap(23, 23, 23)
                                .addComponent(CampoDeTexto_CNPJ))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Painel_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JL_Nome2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CampoDeTexto_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_Cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_Entrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BT_ExcluirUsuario)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BT_ExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_MenuEmpresas)
                .addGap(18, 18, 18)
                .addComponent(Painel_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_Nome2)
                    .addComponent(CampoDeTexto_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoDeTexto_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_CNPJ))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Cadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_Entrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CampoDeTexto_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDeTexto_PesquisaActionPerformed
        Lista.setVisible(true);
        Enter = 1;
    }//GEN-LAST:event_CampoDeTexto_PesquisaActionPerformed

    private void CampoDeTexto_PesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoDeTexto_PesquisaKeyReleased
        if(Enter == 0){
            ListaDePesquisa();
        }
        else{
            Enter = 0;
        }
    }//GEN-LAST:event_CampoDeTexto_PesquisaKeyReleased

    private void ListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMousePressed
        MostrarPesquisa();
        Lista.setVisible(true);
    }//GEN-LAST:event_ListaMousePressed

    private void BT_Cadastrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Cadastrar1MouseClicked
        Main.Main.controller.CadastrarEmpresa(CampoDeTexto_Nome.getText(), CampoDeTexto_CNPJ.getText());
    }//GEN-LAST:event_BT_Cadastrar1MouseClicked

    private void BT_VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_VoltarMouseClicked
        Main.Main.controller.LoginUsuarioVoltar();
    }//GEN-LAST:event_BT_VoltarMouseClicked

    private void Painel_PesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Painel_PesquisaMouseClicked
        Lista.setVisible(false);
        
        ModeloLista = new DefaultListModel();
        
        Lista.setModel(ModeloLista);
        
        Enter = 0;
    }//GEN-LAST:event_Painel_PesquisaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Lista.setVisible(false);
        
        ModeloLista = new DefaultListModel();
        
        Lista.setModel(ModeloLista);
        
        Enter = 0;
    }//GEN-LAST:event_formMouseClicked

    private void BT_Entrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_Entrar1MouseClicked
        boolean verifica = Main.Main.controller.BotaoLogarEmpresa(CampoDeTexto_Nome.getText(), CampoDeTexto_CNPJ.getText());
        if(verifica == true){
            Main.Main.controller.MenuFuncionarios(CampoDeTexto_Nome.getText(), CampoDeTexto_CNPJ.getText());
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuario ou senha inválidas!");
        }
    }//GEN-LAST:event_BT_Entrar1MouseClicked

    private void BT_ExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ExcluirMouseClicked
        Main.Main.controller.excluirEmpresa(CampoDeTexto_Nome.getText(), CampoDeTexto_CNPJ.getText());
    }//GEN-LAST:event_BT_ExcluirMouseClicked

    private void BT_ExcluirUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ExcluirUsuarioMouseClicked
        Main.Main.controller.excluirUsuario();
    }//GEN-LAST:event_BT_ExcluirUsuarioMouseClicked

    private void CampoDeTexto_PesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoDeTexto_PesquisaMouseClicked
        if(Enter == 0){
            ListaDePesquisa();
        }
        else{
            Enter = 0;
        }
    }//GEN-LAST:event_CampoDeTexto_PesquisaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cadastrar1;
    private javax.swing.JButton BT_Entrar1;
    private javax.swing.JButton BT_Excluir;
    private javax.swing.JButton BT_ExcluirUsuario;
    private javax.swing.JButton BT_Voltar;
    private javax.swing.JTextField CampoDeTexto_CNPJ;
    private javax.swing.JTextField CampoDeTexto_Nome;
    private javax.swing.JTextField CampoDeTexto_Pesquisa;
    private javax.swing.JLabel JL_CNPJ;
    private javax.swing.JLabel JL_Lupa;
    private javax.swing.JLabel JL_MenuEmpresas;
    private javax.swing.JLabel JL_Nome2;
    private javax.swing.JList<String> Lista;
    private javax.swing.JPanel Painel_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
